env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
# parserOptions:
#   ecmaVersion: 2018
#   sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  max-len:
    - warn
    - 120
  no-await-in-loop:
    - error
  array-callback-return:
    - warn
  curly:
    - error
  default-case:
    - error
  no-template-curly-in-string:
    - error
  consistent-return:
    - error
  dot-notation:
    - warn
  eqeqeq:
    - error
  guard-for-in:
    - warn
  no-caller:
    - error
  no-case-declarations:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-fallthrough:
    - warn
  no-floating-decimal:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-implicit-coercion:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - warn
  no-multi-str:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-proto:
    - error
  no-return-assign:
    - error
  no-return-await:
    - error
  no-script-url:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-unmodified-loop-condition:
    - warn
  no-useless-call:
    - error
  no-useless-catch:
    - error
  no-useless-escape:
    - warn
  prefer-named-capture-group:
    - warn
  prefer-promise-reject-errors:
    - error
  radix:
    - error
  require-await:
    - warn
  require-unicode-regexp:
    - warn
  no-label-var:
    - warn
  no-shadow:
    - error
  no-use-before-define:
    - error
  handle-callback-err:
    - warn
  no-buffer-constructor:
    - error
  no-mixed-requires:
    - error
  no-new-require:
    - error
  no-path-concat:
    - error
  max-params:
    - warn
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  nonblock-statement-body-position:
    - error
  object-curly-newline:
    - error
  object-curly-spacing:
    - error
  object-property-newline:
    - error
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
  semi-style:
    - error
    - last
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - always
  space-in-parens:
    - error
    - never
  # space-unary-ops
  spaced-comment:
    - error
    - always
  switch-colon-spacing:
    - error
  template-tag-spacing:
    - error
    - never
  arrow-spacing:
    - error
  arrow-parens:
    - warn
  arrow-body-style:
    - warn
  generator-star-spacing:
    - error
  no-confusing-arrow:
    - error
  no-duplicate-imports:
    - error
  no-useless-constructor:
    - error
  template-curly-spacing:
    - error
    - never
  yield-star-spacing:
    - error