variables:
  nodeVersion: '12.x'

trigger:
  branches:
    include:
      - master

stages:

  - stage: Development
    displayName: Development
    jobs:
      - job: Lint
        displayName: Lint Source
        steps:
          - task: NodeTool@0
            displayName: 'Install NodeJS'
            inputs:
              versionSpec: $(nodeVersion)
          - task: Npm@1
            displayName: 'Install NodeJS Dependencies'
            inputs:
              command: install
          - task: CmdLine@2
            displayName: 'Run ESLint'
            inputs:
              script: 'npx eslint --config .eslintrc.yml ./source/*.ts'
      - template: .azure-pipelines/test.yml
        parameters:
          nodeVersion: $(nodeVersion)
          vmImage: 'ubuntu-18.04'
      # - job: pushToMasterBranch
      #   displayName: Push to the Master branch on the Git Repository
      #   dependsOn: Test
      #   steps:
      #     - task: GitHubRelease@0
      #       inputs:
      #         gitHubConnection: ''
      #         repositoryName: ''
      #         action: create
      #         # TODO: Review options. There are a lot more:
      #         # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops
      # - job: publishNPMPackage
      #   displayName: Publish NPM Package
      #   dependsOn: Test
      #   steps:
      #     - task: Npm@1
      #       inputs:
      #         command: publish
      #         publishRegistry: useFeed
      #         publishFeed: ''
      # - job: deployDockerImage
      #   displayName: Deploy Docker Image
      #   dependsOn: Test
      #   steps:
      #     - task: Docker@2
      #       displayName: Build and push an image to container registry
      #       inputs:
      #         command: buildAndPush
      #         repository: $(imageRepository)
      #         dockerfile: $(dockerfilePath)
      #         containerRegistry: $(dockerRegistryServiceConnection)
      #         tags: $(tag)
