---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: blob24
  namespace: default
  labels:
    preql.tech/fullSingularName: '24-bit Length Indicator Blob'
    preql.tech/fullPluralName: '24-bit Length Indicator Blobs'
    preql.tech/standard: 'true'
    preql.tech/category: 'Binary'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'Variable-length bytes array whose length is indicated by an 24-bit unsigned integer.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    # preql.tech/exampleValue: ''
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 16777215
  targets:
    bson:
      nativeType: 'binData'
    cql:
      nativeType: 'blob'
    elasticsearch:
      nativeType: 'binary'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'BLOB'
    mysql:
      nativeType: 'BLOB'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.40'
      ldapMatchingRule: 'octetStringMatch'
      ldapOrderingRule: 'octetStringOrderingMatch'
    plsql:
      nativeType: 'BLOB'
    postgresql:
      nativeType: 'bytea'
    sqlite:
      nativeType: 'BLOB'
    tsql:
      nativeType: 'binary'
