---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: cdi32
  namespace: default
  labels:
    preql.tech/fullSingularName: '32-Bit Context-Dependent Identifier'
    preql.tech/fullPluralName: '32-Bit Context-Dependent Identifiers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    preql.tech/storageSizeInBytes: '8'
    preql.tech/bits: '32'
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'The 32-Bit Context-Dependent Identifier, as defined by the IEEE, stored as a hexadecimal string.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '01020304'
spec:
  jsonEquivalent: 'string'
  minLength: 8
  maxLength: 8
  regexes:
    pcre:
      eui48:
        - pattern: '^[A-F0-9]{8}'
          positive: True
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'replace'
      from: ':'
      to: ''
    - type: 'replace'
      from: '-'
      to: ''
    - type: 'replace'
      from: '.'
      to: ''
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(8)'
    mysql:
      nativeType: 'CHAR(8)'
    openldap:
      # TODO: Change this to a more restricted type. NumericString or PrintableString.
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(8 CHAR)'
    postgresql:
      nativeType: 'char(8)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(8)'
