---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: char4
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Fixed-length 4-character string'
    preql.tech/fullPluralName: 'Fixed-length 4-character strings'
    preql.tech/standard: 'true'
    preql.tech/category: 'String'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A string that contains 4 characters.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'EXAM'
spec:
  jsonEquivalent: 'string'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(4)'
    mysql:
      nativeType: 'CHAR(4)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'NCHAR(4 CHAR)'
    postgresql:
      nativeType: 'char(4)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'NCHAR(4)'
