---
# The 255-character limit is chosen simply because there are limited
# circumstances in which Active Directory would not accept a
# distinguished name greater than 255 characters.
# See: https://stackoverflow.com/questions/20360360/how-long-maximum-characters-is-an-ldap-distinguished-name
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: dn
  namespace: default
  labels:
    preql.tech/fullSingularName: 'X.500 Distinguished Name'
    preql.tech/fullPluralName: 'X.500 Distinguished Names'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A hierarchical identifier that identifies an entry in an X.500-based directory.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'cn=Jonathan Wilbur,dc=wilbur,dc=space'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 255
  regexes:
    pcre:
      dn:
        - pattern: '^[^#]\\p{X}+=\\p{X}+'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(255)'
    mysql:
      nativeType: 'VARCHAR(255)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(255 CHAR)'
    postgresql:
      nativeType: 'varchar(255)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'NVARCHAR(255)'
