---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: dnsRecordType
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Domain Name System Resource Record Type'
    preql.tech/fullPluralName: 'Domain Name System Resource Record Types'
    preql.tech/standard: 'true'
    # preql.tech/category: ''
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'The alphanumeric representation of any DNS resource record type registered with IANA.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    preql.tech/definingSpecificationURI: 'https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml'
    preql.tech/exampleValue: 'SSHFP'
spec:
  jsonEquivalent: 'string'
  name: rrtype
  values:
    - 'A'
    - 'NS'
    - 'MD'
    - 'MF'
    - 'CNAME'
    - 'SOA'
    - 'MB'
    - 'MG'
    - 'MR'
    - 'NULL'
    - 'WKS'
    - 'PTR'
    - 'HINFO'
    - 'MINFO'
    - 'MX'
    - 'TXT'
    - 'RP'
    - 'AFSDB'
    - 'X25'
    - 'ISDN'
    - 'RT'
    - 'NSAP'
    - 'NSAP-PTR'
    - 'SIG'
    - 'KEY'
    - 'PX'
    - 'GPOS'
    - 'AAAA'
    - 'LOC'
    - 'NXT'
    - 'EID'
    - 'NIMLOC'
    - 'SRV'
    - 'ATMA'
    - 'NAPTR'
    - 'KX'
    - 'CERT'
    - 'A6'
    - 'DNAME'
    - 'SINK'
    - 'OPT'
    - 'APL'
    - 'DS'
    - 'SSHFP'
    - 'IPSECKEY'
    - 'RRSIG'
    - 'NSEC'
    - 'DNSKEY'
    - 'DHCID'
    - 'NSEC3'
    - 'NSEC3PARAM'
    - 'TLSA'
    - 'SMIMEA'
    - 'HIP'
    - 'NINFO'
    - 'RKEY'
    - 'TALINK'
    - 'CDS'
    - 'CDNSKEY'
    - 'OPENPGPKEY'
    - 'CSYNC'
    - 'ZONEMD'
    - 'SPF'
    - 'UINFO'
    - 'UID'
    - 'GID'
    - 'UNSPEC'
    - 'NID'
    - 'L32'
    - 'L64'
    - 'LP'
    - 'EUI48'
    - 'EUI64'
    - 'TKEY'
    - 'TSIG'
    - 'IXFR'
    - 'AXFR'
    - 'MAILB'
    - 'MAILA'
    - 'URI'
    - 'CAA'
    - 'AVC'
    - 'DOA'
    - 'AMTRELAY'
    - 'TA'
    - 'DLV'
