---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: duns
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Data Universal Numbering System Number'
    preql.tech/fullPluralName: 'Data Universal Numbering System Numbers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Integer'
    preql.tech/storageSizeInBytes: '8'
    preql.tech/bits: '64'
    preql.tech/signed: 'false'
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: >
      A nine-digit unsigned identifier allocated by Dun & Bradstreet to
      identify a business entity.
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '12345'
spec:
  jsonEquivalent: 'integer'
  minimum: 0
  maximum: 999999999
  targets:
    bson:
      nativeType: 'integer'
    cql:
      nativeType: 'int'
    elasticsearch:
      nativeType: 'integer'
    json:
      nativeType: 'integer'
    mariadb:
      nativeType: 'BIGINT UNSIGNED'
    mysql:
      nativeType: 'BIGINT UNSIGNED'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.27'
      ldapMatchingRule: 'integerMatch'
      ldapOrderingRule: 'integerOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
