---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: fqdn
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Fully-Qualified Domain Name'
    preql.tech/fullPluralName: 'Fully-Qualified Domain Names'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: >
      A Domain Name System-based name for a host or subdomain that concatenates
      the entire hierarchy of DNS labels up to and (implicitly) including the
      root zone label.
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'jonathan.wilbur.space'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 255
  regexes:
    pcre:
      label:
        - pattern: >
            ^(\\p{L}|\\p{N})(?:(\\p{L}|\\p{N}|-){0,61}(\\p{L}|\\p{N}))?(?:\\.(\\p{L}|\\p{N})(?:(\\p{L}|\\p{N}|-){0,61}(\\p{L}|\\p{N}))?)*
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(255)'
    mysql:
      nativeType: 'VARCHAR(255)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(255 CHAR)'
    postgresql:
      nativeType: 'varchar(255)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'NVARCHAR(255)'
