---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: gtin12
  namespace: default
  labels:
    preql.tech/fullSingularName: '12-Digit Global Trade Item Number'
    preql.tech/fullPluralName: '12-Digit Global Trade Item Numbers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A 12-Digit Global Trade Item Number, as specified by GS1.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '19235234'
spec:
  jsonEquivalent: 'string'
  minLength: 12
  maxLength: 12
  regexes:
    pcre:
      gtin:
        - pattern: '^\\d{12}'
          positive: True
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(12)'
    mysql:
      nativeType: 'VARCHAR(12)'
    openldap:
      # TODO: Make this an INTEGER or NumericString
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(12 CHAR)'
    postgresql:
      nativeType: 'varchar(12)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(12)'

