---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: handle
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Handle'
    preql.tech/fullPluralName: 'Handles'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifier'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A username or "handle" for a Twitter, Discord, Gab, or other account that uses similar usernames.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'jonathanwilbur'
spec:
  jsonEquivalent: 'string'
  minLength: 15
  maxLength: 15
  regexes:
    pcre:
      handle:
        - pattern: '^\w{15}'
          positive: True
  setters:
    - type: 'trim'
      side: 'both'
    # Twitter handles ARE case sensitive, so upper-casing is not an option.
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(15)'
    mysql:
      nativeType: 'VARCHAR(15)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(15 CHAR)'
    postgresql:
      nativeType: 'varchar(15)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(15)'

