---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: hour
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Hour'
    preql.tech/fullPluralName: 'Hour'
    preql.tech/standard: 'true'
    preql.tech/category: 'Time'
    preql.tech/storageSizeInBytes: '1'
    preql.tech/bits: '8'
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'An hour on the 24-hour clock.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '15'
spec:
  jsonEquivalent: 'integer'
  minimum: 0
  maximum: 23
  targets:
    bson:
      nativeType: 'integer'
    cql:
      nativeType: 'int'
    elasticsearch:
      nativeType: 'integer'
    json:
      nativeType: 'integer'
    mariadb:
      nativeType: 'TINYINT UNSIGNED'
    mysql:
      nativeType: 'TINYINT UNSIGNED'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.27'
      ldapMatchingRule: 'integerMatch'
      ldapOrderingRule: 'integerOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
    postgresql:
      nativeType: 'smallint'
    sqlite:
      nativeType: 'INTEGER'
    tsql:
      nativeType: 'smallint'
