---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: iban
  namespace: default
  labels:
    preql.tech/fullSingularName: 'International Bank Account Number'
    preql.tech/fullPluralName: 'International Bank Account Numbers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A unique identifier that identifies a bank account.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 13616-1:2007'
    preql.tech/definingSpecificationURI: 'https://www.iso.org/standard/41031.html'
    preql.tech/exampleValue: 'FR7630006000011234567890189'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 34
  regexes:
    pcre:
      iban:
        - pattern: '^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}'
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(34)'
    mysql:
      nativeType: 'VARCHAR(34)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR(34 CHAR)'
    postgresql:
      nativeType: 'varchar(34)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(34)'

