---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: ipv4
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Internet Protocol Version 4 Address'
    preql.tech/fullPluralName: 'Internet Protocol Version 4 Addresses'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'An Internet Protocol Version 4 Address.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '127.0.0.1'
spec:
  jsonEquivalent: 'string'
  minLength: 7
  maxLength: 15
  regexes:
    pcre:
      ipv4:
        - pattern: '^(0|(?:1\\d)|(?:1\\d\\d)|(?:2[0-4]\\d)|(?:25[0-5]))(?:\\.(0|(?:1\\d)|(?:1\\d\\d)|(?:2[0-4]\\d)|(?:25[0-5]))){3}'
          positive: True
  setters:
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'ip'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(15)'
    mysql:
      nativeType: 'VARCHAR(15)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(15 CHAR)'
    postgresql:
      nativeType: 'inet'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(15)'
