---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: iqn
  namespace: default
  labels:
    preql.tech/fullSingularName: 'iSCSI Qualified Name'
    preql.tech/fullPluralName: 'iSCSI Qualified Names'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'An identifier for an iSCSI target.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'IETF RFC 3720'
    preql.tech/definingSpecificationURI: 'https://tools.ietf.org/html/rfc3720#section-3.2.6'
    preql.tech/exampleValue: 'iqn.2001-04.com.example:storage:diskarrays-sn-a8675309'
spec:
  jsonEquivalent: 'string'
  minLength: 13
  maxLength: 128
  regexes:
    pcre:
      iqn:
        - pattern: '^iqn.[12]\\d{3}-[01]\\d(?:\\.(\\p{L}|\\p{N})(?:(\\p{L}|\\p{N}|-){0,61}(\\p{L}|\\p{N}))?)+(?:\\p{X}*)?$'
          positive: True
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(128)'
    mysql:
      nativeType: 'VARCHAR(128)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(128 CHAR)'
    postgresql:
      nativeType: 'varchar(128)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(128)'

