---
# From RFC 3987
# scheme = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: iriSchema
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Internationalized Resource Identifier Schema'
    preql.tech/fullPluralName: 'Internationalized Resource Identifier Schema'
    preql.tech/standard: 'true'
    # preql.tech/category: ''
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: >
      The part of a Internationalized Resource Identifier before the colon.
      This also suffices for a Uniform Resource Identifier.
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'IETF RFC 3987'
    preql.tech/definingSpecificationURI: 'https://tools.ietf.org/html/rfc3987'
    preql.tech/exampleValue: 'http'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 16
  regexes:
    pcre:
      schema:
        - pattern: '^[A-Z][A-Z0-9+\\-\\.]*'
          positive: True
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(16)'
    mysql:
      nativeType: 'VARCHAR(16)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(16 CHAR)'
    postgresql:
      nativeType: 'varchar(16)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'NVARCHAR(16)'
