---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: isil
  namespace: default
  labels:
    preql.tech/fullSingularName: 'International Standard Identifier for Libraries and Related Organizations'
    preql.tech/fullPluralName: 'International Standard Identifiers for Libraries and Related Organizations'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    preql.tech/storageSizeInBytes: '16'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A unique identifier that identifies libraries and related organisations, such as archives and museums.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 15511:2019'
    preql.tech/definingSpecificationURI: 'https://www.iso.org/standard/77849.html'
    preql.tech/exampleValue: '0852-08502802'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 16
  regexes:
    pcre:
      isil:
        - pattern: '^[A-Z0-9/:]+-[A-Z0-9/:]+'
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(16)'
    mysql:
      nativeType: 'VARCHAR(16)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR(16 CHAR)'
    postgresql:
      nativeType: 'varchar(16)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(16)'

