---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: isli
  namespace: default
  labels:
    preql.tech/fullSingularName: 'International Standard Link Identifier'
    preql.tech/fullPluralName: 'International Standard Link Identifier'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    preql.tech/storageSizeInBytes: '9'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'An identifier of links between entities (or their names) in the field of information and documentation.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 17316:2015'
    preql.tech/definingSpecificationURI: 'https://www.iso.org/standard/59560.html'
    preql.tech/exampleValue: 'ISLI 123456-12345-1'
spec:
  jsonEquivalent: 'string'
  minLength: 19
  maxLength: 19
  regexes:
    pcre:
      nsin:
        - pattern: '^ISLI \\d{6}-\\d{5}-\\d$'
          positive: True
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(19)'
    mysql:
      nativeType: 'CHAR(19)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(19 CHAR)'
    postgresql:
      nativeType: 'char(19)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(19)'

