---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: ismn
  namespace: default
  labels:
    preql.tech/fullSingularName: 'International Standard Music Number'
    preql.tech/fullPluralName: 'International Standard Music Numbers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    preql.tech/storageSizeInBytes: '13'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A unique identifier that identifies a musical work.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 10957:2009'
    preql.tech/definingSpecificationURI: 'https://www.iso.org/standard/43173.html'
    preql.tech/exampleValue: '9783161484100'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 13
  regexes:
    pcre:
      ismn:
        - pattern: '^\\d{13}'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(13)'
    mysql:
      nativeType: 'CHAR(13)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(13 CHAR)'
    postgresql:
      nativeType: 'char(13)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(13)'

