---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: isni
  namespace: default
  labels:
    preql.tech/fullSingularName: 'International Standard Name Identifier'
    preql.tech/fullPluralName: 'International Standard Name Identifiers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    preql.tech/storageSizeInBytes: '16'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: >
      An identifier for uniquely identifying the public identities of
      contributors to media content such as books, television programmes, and
      newspaper articles.
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 27729:2012'
    preql.tech/definingSpecificationURI: 'https://www.iso.org/standard/44292.html'
    preql.tech/exampleValue: '9783161484100123'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 16
  regexes:
    pcre:
      isni:
        - pattern: '^\\d{16}'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(16)'
    mysql:
      nativeType: 'CHAR(16)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(16 CHAR)'
    postgresql:
      nativeType: 'char(16)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(16)'

