---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: iso3166-2
  namespace: default
  labels:
    preql.tech/fullSingularName: 'ISO 3166-2 Administrative Subdivision Code'
    preql.tech/fullPluralName: 'ISO 3166-2 Administrative Subdivision Codes'
    preql.tech/standard: 'true'
    preql.tech/category: 'Geography'
    # preql.tech/storageSizeInBytes: '5'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'Two-Letter Country Codes, as specified in ISO 3166-1.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 3166-1'
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'US-FL'
spec:
  jsonEquivalent: 'string'
  minLength: 4
  maxLength: 8
  regexes:
    pcre:
      iso:
        - pattern: '^[A-Z]{2}-[A-Z0-9]+'
          positive: True
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(8)'
    mysql:
      nativeType: 'VARCHAR(8)'
    openldap:
      # TODO: Make it PrintableString or IA5String
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR(8 CHAR)'
    postgresql:
      nativeType: 'varchar(8)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(8)'
