---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: iso3166-1-numeric
  namespace: default
  labels:
    preql.tech/fullSingularName: 'ISO 3166-1 Numeric Country Code'
    preql.tech/fullPluralName: 'ISO 3166-1 Numeric Country Codes'
    preql.tech/standard: 'true'
    preql.tech/category: 'Geography'
    preql.tech/storageSizeInBytes: '2'
    preql.tech/bits: '16'
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'Numeric Country Codes, as specified in ISO 3166-1.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 3166-1'
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '999'
spec:
  jsonEquivalent: 'integer'
  minimum: 0
  maximum: 999
  targets:
    bson:
      nativeType: 'integer'
    cql:
      nativeType: 'int'
    elasticsearch:
      nativeType: 'integer'
    json:
      nativeType: 'integer'
    mariadb:
      nativeType: 'SMALLINT UNSIGNED'
    mysql:
      nativeType: 'SMALLINT UNSIGNED'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.27'
      ldapMatchingRule: 'integerMatch'
      ldapOrderingRule: 'integerOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
    postgresql:
      nativeType: 'smallint'
    sqlite:
      nativeType: 'INTEGER'
    tsql:
      nativeType: 'smallint'
