---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: iso3166-1-alpha-3
  namespace: default
  labels:
    preql.tech/fullSingularName: 'ISO 3166-1 Three-Letter Country Code'
    preql.tech/fullPluralName: 'ISO 3166-1 Three-Letter Country Codes'
    preql.tech/standard: 'true'
    preql.tech/category: 'Geography'
    preql.tech/storageSizeInBytes: '3'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'Two-Letter Country Codes, as specified in ISO 3166-1.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 3166-1'
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'USA'
spec:
  jsonEquivalent: 'string'
  minLength: 3
  maxLength: 3
  regexes:
    pcre:
      iso:
        - pattern: '^[A-Z]{3}'
          positive: True
  setters:
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(3)'
    mysql:
      nativeType: 'CHAR(3)'
    openldap:
      # TODO: Make it PrintableString or IA5String
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(3 CHAR)'
    postgresql:
      nativeType: 'char(3)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(3)'
