---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: lei
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Legal Entity Identifier'
    preql.tech/fullPluralName: 'Legal Entity Identifiers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A unique identifier that identifies a bank account.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    preql.tech/definingSpecification: 'ISO 17442:2019'
    preql.tech/definingSpecificationURI: 'https://www.iso.org/standard/75998.html'
    preql.tech/exampleValue: '54930084UKLVMY22DS16'
spec:
  jsonEquivalent: 'string'
  minLength: 20
  maxLength: 20
  regexes:
    pcre:
      lei:
        - pattern: '^[A-Z0-9]{20}'
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(20)'
    mysql:
      nativeType: 'CHAR(20)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(20 CHAR)'
    postgresql:
      nativeType: 'char(20)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(20)'

