---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: money
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Money'
    preql.tech/fullPluralName: 'Monies'
    preql.tech/standard: 'true'
    preql.tech/category: 'Money'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    preql.tech/signed: 'true'
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A representation of a quantity of money.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '25.10'
spec:
  jsonEquivalent: 'number'
  targets:
    bson:
      nativeType: 'number'
    cql:
      nativeType: 'double'
    elasticsearch:
      nativeType: 'double'
    json:
      nativeType: 'number'
    mariadb:
      nativeType: 'DOUBLE SIGNED'
    mysql:
      nativeType: 'DOUBLE SIGNED'
    # Unfortunately, OpenLDAP does not seem to support the ASN.1 REAL
    # type for whatever reason, so we have to use a string type to
    # represent numbers that can be non-integral, such as:
    # - 123
    # - 1.23
    # - 1.23 * 10^-1
    # - 1.23E-1
    # - +4.56
    # - Infinity
    # - -Infinity
    # - NaN
    # - 5 + 3i
    # - PI
    # - 5 / 3
    #
    # Hence, I have chosen PrintableString.
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.44'
      ldapMatchingRule: 'caseIgnoreIA5Match'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
    postgresql:
      nativeType: 'double precision'
    sqlite:
      nativeType: 'REAL'
    tsql:
      # Even though Transact-SQL has a 'money' data type, this StackOverflow
      # answer should talk you out of ever using it:
      # https://stackoverflow.com/questions/582797/should-you-choose-the-money-or-decimalx-y-datatypes-in-sql-server
      nativeType: 'double'

