---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: nsin
  namespace: default
  labels:
    preql.tech/fullSingularName: 'National Securities Identifying Number'
    preql.tech/fullPluralName: 'National Securities Identifying Numbers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    preql.tech/storageSizeInBytes: '9'
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A unique identifier that identifies a securities trading exchange.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    # preql.tech/exampleValue: ''
spec:
  jsonEquivalent: 'string'
  minLength: 9
  maxLength: 9
  regexes:
    pcre:
      nsin:
        - pattern: '^[A-Z0-9]{9}$'
          positive: True
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(9)'
    mysql:
      nativeType: 'CHAR(9)'
    openldap:
      # TODO: Make this NumericString or Integer
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(9 CHAR)'
    postgresql:
      nativeType: 'char(9)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'CHAR(9)'

