---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: phone
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Phone Number'
    preql.tech/fullPluralName: 'Phone Numbers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A number used to address and communicate with a telephone.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '3521230009'
spec:
  jsonEquivalent: 'string'
  minLength: 1
  maxLength: 16
  regexes:
    pcre:
      name:
        - pattern: '^\\d+'
          positive: True
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'replace'
      from: '('
      to: ''
    - type: 'replace'
      from: ')'
      to: ''
    - type: 'replace'
      from: '+'
      to: ''
    - type: 'replace'
      from: '-'
      to: ''
    - type: 'replace'
      from: '.'
      to: ''
    - type: 'replace'
      from: ' '
      to: ''
    # - type: 'replace'
    #   from: '#'
    #   to: ''
    # - type: 'replace'
    #   from: '*'
    #   to: ''
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(16)'
    mysql:
      nativeType: 'VARCHAR(16)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(16 CHAR)'
    postgresql:
      nativeType: 'varchar(16)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(16)'
