---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: sint32
  namespace: default
  labels:
    preql.tech/fullSingularName: '32-Bit Signed Integer'
    preql.tech/fullPluralName: '32-Bit Signed Integers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Integer'
    preql.tech/storageSizeInBytes: '4'
    preql.tech/bits: '32'
    preql.tech/signed: 'true'
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A signed integer that can range between -2,147,483,648 and 2,147,483,647.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '-32,760'
spec:
  jsonEquivalent: 'integer'
  minimum: -2147483648
  maximum: 2147483647
  targets:
    bson:
      nativeType: 'integer'
    cql:
      nativeType: 'int'
    elasticsearch:
      nativeType: 'integer'
    json:
      nativeType: 'integer'
    mariadb:
      nativeType: 'INTEGER'
    mysql:
      nativeType: 'INTEGER'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.27'
      ldapMatchingRule: 'integerMatch'
      ldapOrderingRule: 'integerOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
    postgresql:
      nativeType: 'integer'
    sqlite:
      nativeType: 'INTEGER'
    tsql:
      nativeType: 'integer'
