---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: sint64
  namespace: default
  labels:
    preql.tech/fullSingularName: '64-Bit Signed Integer'
    preql.tech/fullPluralName: '64-Bit Signed Integers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Integer'
    preql.tech/storageSizeInBytes: '8'
    preql.tech/bits: '64'
    preql.tech/signed: 'true'
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A signed integer that can range between -9223372036854775808 and 9223372036854775807.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '-32,760'
spec:
  jsonEquivalent: 'integer'
  minimum: -9223372036854775808
  maximum: 9223372036854775807
  targets:
    bson:
      nativeType: 'integer'
    cql:
      nativeType: 'int'
    elasticsearch:
      nativeType: 'integer'
    json:
      nativeType: 'integer'
    mariadb:
      nativeType: 'BIGINT'
    mysql:
      nativeType: 'BIGINT'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.27'
      ldapMatchingRule: 'integerMatch'
      ldapOrderingRule: 'integerOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
    postgresql:
      nativeType: 'bigint'
    sqlite:
      nativeType: 'INTEGER'
    tsql:
      nativeType: 'bigint'
