---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: timeZone
  namespace: default
  labels:
    preql.tech/fullSingularName: 'IANA TimeZone'
    preql.tech/fullPluralName: 'IANA Timezones'
    preql.tech/standard: 'true'
    preql.tech/category: 'Geography'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'Timezone identifiers taken from the TZ Database published by IANA.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'America/North_Dakota/New_Salem'
spec:
  jsonEquivalent: 'string'
  minLength: 3
  maxLength: 64
  regexes:
    pcre:
      tz:
        - pattern: '^[A-Z][A-Z_]*[A-Z]/[A-Z][A-Z_]*[A-Z](?:/[A-Z][A-Z_]*[A-Z])?'
          positive: True
  setters:
    - type: 'trim'
      side: 'both'
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(64)'
    mysql:
      nativeType: 'VARCHAR(64)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(64 CHAR)'
    postgresql:
      nativeType: 'varchar(64)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'VARCHAR(64)'
