---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: uint64
  namespace: default
  labels:
    preql.tech/fullSingularName: '64-Bit Unsigned Integer'
    preql.tech/fullPluralName: '64-Bit Unsigned Integers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Integer'
    preql.tech/storageSizeInBytes: '8'
    preql.tech/bits: '64'
    preql.tech/signed: 'false'
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'An unsigned integer that can range between 0 and 18,446,744,073,709,551,615.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '12345'
spec:
  jsonEquivalent: 'integer'
  minimum: 0
  maximum: 18446744073709551615
  targets:
    bson:
      nativeType: 'integer'
    cql:
      nativeType: 'int'
    elasticsearch:
      nativeType: 'integer'
    json:
      nativeType: 'integer'
    mariadb:
      nativeType: 'BIGINT UNSIGNED'
    mysql:
      nativeType: 'BIGINT UNSIGNED'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.27'
      ldapMatchingRule: 'integerMatch'
      ldapOrderingRule: 'integerOrderingMatch'
    plsql:
      nativeType: 'NUMBER'
