---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: uuid
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Universally-Unique Identifier'
    preql.tech/fullPluralName: 'Universally-Unique Identifiers'
    preql.tech/standard: 'true'
    preql.tech/category: 'Identifiers'
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'A Universally-Unique Identifier.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: '8747f03d-0566-4f54-b787-ac80fda72a8d'
spec:
  jsonEquivalent: 'string'
  minLength: 36
  maxLength: 36
  regexes:
    pcre:
      uuid:
        - pattern: '^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'
          positive: True
  setters:
    - type: 'case'
      casing: 'upper'
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'uuid'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'CHAR(36)'
    mysql:
      nativeType: 'CHAR(36)'
    openldap:
      nativeType: '1.3.6.1.1.16.1' # https://tools.ietf.org/html/rfc4530#section-2.1
      ldapMatchingRule: 'uuidMatch'
      ldapOrderingRule: 'uuidOrderingMatch'
      # nativeType: '1.3.6.1.4.1.1466.115.121.1.44'
      # ldapMatchingRule: 'caseIgnoreMatch'
      # ldapOrderingRule: 'caseIgnoreOrderingMatch'
      # ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'CHAR(36 CHAR)'
    postgresql:
      nativeType: 'uuid'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'NCHAR(36)'
