---
apiVersion: preql/1.0.0
kind: DataType
metadata:
  name: windowsFileName
  namespace: default
  labels:
    preql.tech/fullSingularName: 'Windows File Name'
    preql.tech/fullPluralName: 'Windows File Names'
    preql.tech/standard: 'true'
    # preql.tech/category: ''
    # preql.tech/storageSizeInBytes: ''
    # preql.tech/bits: ''
    # preql.tech/signed: ''
    # preql.tech/country: ''
    # preql.tech/objectIdentifier: ''
    # preql.tech/uuid: ''
  annotations:
    preql.tech/description: 'The name of a file on a Windows operating system.'
    preql.tech/author: 'Jonathan M. Wilbur'
    preql.tech/authorEmailAddress: 'jonathan@wilbur.space'
    # preql.tech/definingSpecification: ''
    # preql.tech/definingSpecificationURI: ''
    preql.tech/exampleValue: 'test.bat'
spec:
  jsonEquivalent: 'string'
  minLength: 0
  maxLength: 260
  regexes:
    pcre:
      name:
        # Source: https://stackoverflow.com/a/6804755/6562635
        - pattern: >
            ^[^<>:\"/\\\\|?*\\x00-\\x1F]{0,259}[^<>:\"/\\\\|?*\\x00-\\x1F\\ .]
          positive: True
        - pattern: ^(?:CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\\.[^.]*)?
          positive: False
  targets:
    bson:
      nativeType: 'string'
    cql:
      nativeType: 'text'
    elasticsearch:
      nativeType: 'keyword'
    json:
      nativeType: 'string'
    mariadb:
      nativeType: 'VARCHAR(260)'
    mysql:
      nativeType: 'VARCHAR(260)'
    openldap:
      nativeType: '1.3.6.1.4.1.1466.115.121.1.15'
      ldapMatchingRule: 'caseIgnoreMatch'
      ldapOrderingRule: 'caseIgnoreOrderingMatch'
      ldapSubstringMatchingRule: 'caseIgnoreSubstringsMatch'
    plsql:
      nativeType: 'VARCHAR2(260 CHAR)'
    postgresql:
      nativeType: 'varchar(260)'
    sqlite:
      nativeType: 'TEXT'
    tsql:
      nativeType: 'NVARCHAR(260)'
